# Generated by Django 2.2.5 on 2019-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
