# Generated by Django 2.2.5 on 2019-09-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catapi', '0002_auto_20190924_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catapi.Category'),
        ),
    ]
