# Generated by Django 2.2.5 on 2019-09-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapi', '0003_category_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
